### ISSUE TITLE
Test/Make it compatible with Hestia and Shop Isle

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/WooCommerce-Compare-List#7]
@contactashish13 could you please test this with Hestia and Shop Isle and make sure it works/looks ok with it?

**Comment by contactashish13** [comment]
@rodica-andronache It looks fine more or less. I have fixed a couple of legacy issues.

clunky UI in Hestia & Hestia Pro
![image](https://user-images.githubusercontent.com/12953439/42014421-e384203a-7abf-11e8-81a2-d14247807569.png)

In Hestia Pro, the following error is thrown `WC_Cart::get_cart_url is <strong>deprecated</strong> since version 2.5! Use wc_get_cart_url instead`

**Comment by rodica-andronache** [comment]
@stefan-cotitosu what I would suggest here is to try take another look at the css code you've added in the theme and try to optimize it. The idea is to add the least css possible in the theme now, as the css file is already really big. And in this case, it's even easier as the plugin is ours and we can work in it :)

And I'm not just saying move the whole code specific to Hestia in the plugin. I'm saying that it can be optimized in some way.
For e.g this code added in hestia
`.woocommerce.single-product .wccm-compare-btn {	
  margin: 10px 5px;	
}`
only to override the general 
.wccm-compare-btn
from the plugin.

Adding that more specific selector in the plugin, makes sense, as it's not specific to Hestia anyway. And it would leave hestia without the extra few lines of css.

Another thing that you can do, I think:
You've added many specific selectors like .woocommerce a.wccm-compare-btn in hestia, for the buttons background and other properties. That's ok, but it just adds some new lines in hestia, and no extra value ( than being compatible with this plugin at this point ). What if we want to make Hestia compatible with other plugins that do something similar? We'll add another line of css, with their specific classes? That's not the best approach for the future.
So, what you could do, is try to see if we can have maybe something more general, like  .woocommerce a.button let's say

**Comment by rodica-andronache** [comment]
plus,please move the code from here https://github.com/Codeinwp/WooCommerce-Compare-List/pull/6 to this branch too, so we can merge it. Thanks

**Comment by rodica-andronache** [comment]
@stefan-cotitosu I think I wasn't very clear, sorry. I see you created a new PR.
The idea is that Ash worked on his fork, on production and I wanted to have everything there ( to be able to merge it easy ). https://github.com/Codeinwp/WooCommerce-Compare-List/pull/8
So, you would need to make your changes there, not on a separate branch.

And I also wanted to have the code from here https://github.com/Codeinwp/WooCommerce-Compare-List/pull/6 moved on the same branch. 
If it's still not clear, we can talk, as it will be easier :)

**Comment by rodica-andronache** [comment]
@stefan-cotitosu for the checks for shop isle/zerif make sure you also check for child themes 👍

**Comment by stefan-cotitosu** [comment]
@rodica-andronache It is working with child themes on both Zerif and ShopIsle, pro, lite, wporg version. It seems that there are some issues regarding the compare buttons color, I am waiting for buttons styling to be ready and then I will check them again.
